## Projects - directories to quick-switch into
[[projects]]
name = "Neovim Config"
path = "~/.config/nvim"

[[projects]]
name = "Dotfiles"
path = "~/.config/cli-dots"

[[projects]]
name = "libparametric"
path = "~/Development/parametric/libparametric"

[[projects]]
name = "Convexity API"
path = "~/Development/parametric/convexity-api"

[[projects]]
name = "Convexbox"
path = "~/Development/parametric/convexbox"

[[projects]]
name = "Business Docs"
path = "~/Development/parametric/business-docs"

## Bookmarks - frequently accessed files

[[bookmarks]]
name = "Ghostty Config"
path = "~/.config/ghostty/config"

[[bookmarks]]
name = "Fish Config"
path = "~/.config/fish/fish.conf"


## Orgfiles / Notes
[[orgfiles]]
name = "Notes"
path = "~/org"
